spring:
  application:
    name: airlines-api-gateway
  cloud:
    gateway:
      routes:
      - id: airlines-booking-service
        uri:
          lb://airlines-booking-service
        predicates:
        - Path=/bookings/**
        
      - id: airlines-info-service
        uri:
          lb://airlines-info-service   
        predicates:
        - Path=/flight/** 
        
      - id: airlines-coupon-discounts-service
        uri:
          lb://airlines-coupon-discounts-service
        predicates:
        - Path=/coupon/** 

server:
  port: 8888